### ISSUE TITLE
OnFocus only fires once

### ISSUE THREAD

**Issue by sethomas** [final-form/react-final-form-listeners#2]
`OnFocus` event is only firing once.

Looking at this line:
https://github.com/final-form/react-final-form-listeners/blob/master/src/OnFocus.js#L32

`state.previous` will never be set back to false.

Sorry for not giving you heaps of info, this seems like an easy enough fix.

LOVING final-form and your react wrappers (currently migrating away from redux forms)

**Comment by erikras** [comment]
Published fix in [`v1.0.1`](https://github.com/final-form/react-final-form-listeners/releases/tag/v1.0.1).

**Comment by erikras** [comment]
Don't expect this turn around time on every bug in the future! 😜
