### ISSUE TITLE
Why are these implemented as external listeners rather than in RFF?

### ISSUE THREAD

**Issue by tstirrat15** [final-form/react-final-form-listeners#21]
I noticed that `onBlur` isn't something that you can pass to a `Field`, and that RFF is passing its own `onBlur` through to the underlying `input` instance when I wrap an input.

Then there's this lib, which listens to RFF state to infer whether a field has been focused, rather than tying into the existing lib.

Is there a technical reason for this? Otherwise I'm having a hard time understanding this lib's existence.

**Comment by abrad45** [comment]
Pure conjecture, but breaking these out into another library:

* ...reduces the size of RFF
* ...keeps infrequently used parts of RFF out of the core library
* ...enables the RFF documentation to be smaller and more digestable 
* ...demonstrates how RFF can be extended

**Comment by erikras** [comment]
Yep. What @abrad45 said.
