### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by AntonOfTheWoods** [final-form/react-final-form-listeners#39]
### Are you submitting a **bug report** or a **feature request**?

Feature request

### What is the current behavior?

No react 18

### What is the expected behavior?
React 18

Is there any appetite for official React 18 support, or is 17 the end of the road for rffl?

**Comment by muyiwaoyeniyi** [comment]
+1

**Comment by kg-currenxie** [comment]
Need this too 🙋‍♂️

**Comment by AntonOfTheWoods** [comment]
To the others who come here, I suggest you just do what I did and copy/paste what you actually need into your own code. It is very obvious this repo has been completely abandoned, so you are better forgetting about it and maintaining the code yourselves. There really isn't a lot of code...

**Comment by AntonOfTheWoods** [comment]
To the others who come here, I suggest you just do what I did and copy/paste what you actually need into your own code. It is very obvious this repo has been completely abandoned, so you are better forgetting about it and maintaining the code yourselves. There really isn't a lot of code...
